### ISSUE TITLE
Is the corresponding paper available？ 

### ISSUE THREAD

**Issue by ZSQflower** [longcw/MOTDT#1]
Could you share the corresponding paper with us?

**Comment by joaqo** [comment]
Would really appreciate it too.

**Comment by heurainbow** [comment]
It seems to me the mot_tracker implementation borrows heavily from the deep_sort tracker.

**Comment by liangzimei** [comment]
can anyone share the paper? thanks……

**Comment by tornadomeet** [comment]
here : https://arxiv.org/abs/1809.04427

**Comment by liangzimei** [comment]
@tornadomeet thank you~
