### ISSUE TITLE
ImportError: ./motdt/models/psroi_pooling/_ext/psroi_pooling/_psroi_pooling.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by antocapp** [longcw/MOTDT#20]
>ImportError: ./motdt/models/psroi_pooling/_ext/psroi_pooling/_psroi_pooling.so: undefined symbol: __cudaPopCallConfiguration

How can I resolve this issue? 

I installed pytorch 0.4.1 on a conda env, my cuda version is 10 however since my GPU is a GeForce RTX 2080 Ti.

Please help me

**Comment by clw5180** [comment]
> > ImportError: ./motdt/models/psroi_pooling/_ext/psroi_pooling/_psroi_pooling.so: undefined symbol: __cudaPopCallConfiguration
> 
> How can I resolve this issue?
> 
> I installed pytorch 0.4.1 on a conda env, my cuda version is 10 however since my GPU is a GeForce RTX 2080 Ti.
> 
> Please help me

Same problem. How you solve it?

**Comment by segalinc** [comment]
same here. any fix?
