### ISSUE TITLE
unable to open file: name = 'data/squeezenet_small40_coco_mot16_ckpt_10.h5

### ISSUE THREAD

**Issue by maxtom** [longcw/MOTDT#5]
So where is your pretrained model?
Can you help me fix this problem?

**Comment by maxtom** [comment]
I've seen that right now on the below link. Thank you.

**Comment by dllsjiang** [comment]
I have the same problem, how do you solve it?

**Comment by longcw** [comment]
https://drive.google.com/drive/folders/1ETfqSoy7OeT-8GO75F1bYWhP3mzrwwvn?usp=sharing

**Comment by dllsjiang** [comment]
Thank you!

**Comment by chenrxi** [comment]
can you provide the link such as Baidu Yun?Thank you
